---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /var/games/minecraft/servers/yuki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        role: minecraft
      tolerations:
        - key: "minecraft-only"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: "10G"
            - name: TYPE
              value: "PAPER"
            - name: VERSION
              value: "1.21.4"
          resources:
            requests:
              cpu: "3"
              memory: "6Gi"
            limits:
              cpu: "5"
              memory: "12Gi"
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-pvc
