apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birthday-bot
  template:
    metadata:
      labels:
        app: birthday-bot
    spec:
      containers:
      - name: birthday-bot
        image: your_dockerhub_username/birthday-bot:latest
        imagePullPolicy: Always
