apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-bot
  namespace: discord-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birthday-bot
  template:
    metadata:
      labels:
        app: birthday-bot
    spec:
      containers:
      - name: birthday-bot
        image: vidunvj/birthday-bot:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: tz-config
        hostPath:
          path: /etc/localtime
          type: File

