apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-status-bot
  namespace: discord-bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-status-bot
  template:
    metadata:
      labels:
        app: server-status-bot
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: server-status-bot
          image: vidunvj/server-status-bot:latest
          imagePullPolicy: Always
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-webhook-secret
                  key: DISCORD_TOKEN
            - name: WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: discord-webhook-secret
                  key: DISCORD_WEBHOOK_URL

