version: "3.9"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - USER=admin
      - PASS=password
    volumes:
      - /mnt/media/transmission-config:/config
      - /mnt/media:/media
    restart: unless-stopped
